### ISSUE TITLE
Make the name limit smaller

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#10]
https://discord.com/channels/626715201445691392/699478647454695434/768846647190749184 it breaks the panel

**Comment by TehloWasTaken** [comment]
Please provide actual information instead of linking back to Discord.

**Comment by ElijahRus250** [comment]
![Screen_Shot_2020-10-22_at_10 43 15_AM](https://user-images.githubusercontent.com/64851720/96895672-a56e1800-145a-11eb-8cf3-a4d376b974e9.png)
<img width="1067" alt="Screen Shot 2020-10-22 at 10 41 48 AM" src="https://user-images.githubusercontent.com/64851720/96895379-5a540500-145a-11eb-8e5e-c24684238f9a.png">

when your name is very long it breaks parts of the panel

while it should look like

![Screen_Shot_2020-10-22_at_10 44 02_AM](https://user-images.githubusercontent.com/64851720/96895695-ad2dbc80-145a-11eb-8b0f-c37cc4c94023.png)

![Screen_Shot_2020-10-22_at_10 43 53_AM](https://user-images.githubusercontent.com/64851720/96895721-b159da00-145a-11eb-9f2f-5e1e3ff66dce.png)

**Comment by alliraine** [comment]
Again good catch and much better description.
