### ISSUE TITLE
add a copy all for server information

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#12]
this will be useful to make a template thing for a support ticket

**Comment by TehloWasTaken** [comment]
All you need to give us is a Server ID, from there we can see the rest. I don't really see this having a use to be fair, but maybe @pressstartearly can give his opinion too.

**Comment by alliraine** [comment]
I will give Jeff access to the panel so he can pull this for us before I do this.
