### ISSUE TITLE
Move the change server name

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#13]
You should add it to here: https://discord.com/channels/626715201445691392/699478647454695434/768851015403175977

and it will clear up some more room here: https://discord.com/channels/626715201445691392/699478647454695434/768850988961497139 

I also keep thinking I can type there but I can't

**Comment by TehloWasTaken** [comment]
Please provide actual information instead of linking back to Discord.

**Comment by ElijahRus250** [comment]
You should add it to here: 
<img width="536" alt="Screen_Shot_2020-10-22_at_10 59 21_AM" src="https://user-images.githubusercontent.com/64851720/96895255-3bee0980-145a-11eb-9509-db709ae15ca0.png">

and it will clear up some more room here: 

![Screen_Shot_2020-10-22_at_10 59 15_AM](https://user-images.githubusercontent.com/64851720/96895273-41e3ea80-145a-11eb-81df-0782d941aad1.png)


I also keep thinking I can type there but I can't

**Comment by alliraine** [comment]
Love this idea.

**Comment by ElijahRus250** [comment]
this was changed to be a lot better idk when but it was
