### ISSUE TITLE
Schedules: Add some text saying you will be able to edit what will happen in the schedule after you create it and click on it

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#14]
people will be confused as it is a lot different from last version
https://discord.com/channels/626715201445691392/699478647454695434/768853231995453440

**Comment by TehloWasTaken** [comment]
Please provide actual information instead of linking back to Discord.

**Comment by ElijahRus250** [comment]
<img width="696" alt="Screen_Shot_2020-10-22_at_11 07 43_AM" src="https://user-images.githubusercontent.com/64851720/96895149-1b25b400-145a-11eb-94df-ceff82162338.png">
You can write it below name or beside create

**Comment by alliraine** [comment]
Maybe just rename the button to say continue would be enough. Thoughts @TehloWasTaken

**Comment by alliraine** [comment]
Changed the button to say Continue.
