### ISSUE TITLE
'Launch SFTP

### ISSUE THREAD

**Issue by TehloWasTaken** [DedicatedMC/Raw-Power-Panel#17]

**Comment by TehloWasTaken** [comment]
Gives the following error on Chrome:

`Failed to launch 'sftp://tehlo.44f86c85@dev-daemon-01.rawpower.network:2022' because the scheme does not have a registered handler.`

**Comment by ElijahRus250** [comment]
I get this same issue, I don't really see the reason for it anyway. Maybe just remove it.

**Comment by Firosee** [comment]
Yeah i agree, no real need for it.

**Comment by alliraine** [comment]
This is an issue related to OS and/or browsers

**Comment by BeWog** [comment]
Can't find any solutions with Chrome.

It works with Firefox, it ask me which application to open the SFTP link.

**Comment by EgoMaw** [comment]
As Alli mentioned, this is an issue with certain browsers and/or OS.
You can manually set the default app to handle the sftp scheme in your OS's settings
For Windows 11 it's in Settings → Apps → Default Apps → Choose defaults by link type.

Unfortunately this isn't something we can fix ourselves
