### ISSUE TITLE
When using click to copy on the IP. feature

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#20]
I am not sure how to explain this but when you click to copy it only on IP it hides the address, it should only hide if the hide button is clicked:
![Kapture 2020-10-24 at 12 25 27](https://user-images.githubusercontent.com/64851720/97086901-2ca2c380-15f4-11eb-92ad-0635ff620fb2.gif)

**Comment by alliraine** [comment]
I did this on purpose to help with sizing. It was a lazy fix. I will fix it proper another time.

**Comment by TehloWasTaken** [comment]
I've already created another issue for this, which was already assigned and fixed by TGB. Thanks bb @tgb20 ❤️

**Comment by tgb20** [comment]
@TehloWasTaken This is a different issue in the same area.

**Comment by TehloWasTaken** [comment]
Oh I see, I didn't notice that lol. My bad.

**Comment by pressstartearly** [comment]
Fixed

**Comment by alliraine** [comment]
This is still an issue

**Comment by AriDeve** [comment]
Is it still an issue?
