### ISSUE TITLE
In file manager make it use another line at a certain amount of space

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#22]
for big dir, it breaks the panel. Shown below:

<img width="1181" alt="Screen Shot 2020-10-24 at 12 38 34 PM" src="https://user-images.githubusercontent.com/64851720/97087156-d9317500-15f5-11eb-8446-df87dd72d894.png">

What you can do is after x amount or when it gets to the button it goes to a new line, I could of gone further but then the buttons just disappear.

**Comment by ElijahRus250** [comment]
This is not unless as it can also be just a few larger names files.

<img width="1183" alt="Screen Shot 2020-10-24 at 12 40 35 PM" src="https://user-images.githubusercontent.com/64851720/97087196-1eee3d80-15f6-11eb-80cd-812b6b737091.png">

**Comment by TehloWasTaken** [comment]
If you have _that_ many folders or files you've got issues to begin with 😂

**Comment by ElijahRus250** [comment]
lmfao

**Comment by alliraine** [comment]
![image](https://user-images.githubusercontent.com/57644769/122994107-16612900-d376-11eb-8b87-e2f359675ba7.png)
![image](https://user-images.githubusercontent.com/57644769/122994126-1c570a00-d376-11eb-8434-6ed6daab036c.png)

This is still an issue to some extent

**Comment by EgoMaw** [comment]
This has been fixed in the next panel update. Alli just doesn't like to wrap content 😛
