### ISSUE TITLE
Server Info Page

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#23]
**Describe the bug**
On the panel, not booster panel on the server info page it looks very messed up, no ports or anything with weird sizes

**To Reproduce**
Go to the server info page.

**Expected behavior**
It should look like this:
<img width="1351" alt="Screen Shot 2020-10-25 at 10 17 32 AM" src="https://user-images.githubusercontent.com/64851720/97109752-6256b380-16ab-11eb-9fba-92cbc9f12e3e.png">

**Screenshots**
<img width="1440" alt="Screen Shot 2020-10-25 at 12 54 19 AM" src="https://user-images.githubusercontent.com/64851720/97099212-ecc3f680-165c-11eb-9590-87494ae9eb9e.png">

**If you were on Desktop please provide**
 - Big Sur Beta 11
 - Safari
 - Full Screen

**Additional context**
on the booster panel it works fine, On the main panel not so much. Both were in the same screen resolution

**Comment by alliraine** [comment]
This is just an issue with the reorganization of those panels. This should be redone using grids properly.
