### ISSUE TITLE
Duplicate player counts

### ISSUE THREAD

**Issue by DarklineGaming** [DedicatedMC/Raw-Power-Panel#28]
**Describe the bug**
On the server list, after waiting for a couple minutes each server you have on the panel shows the same amount of players online.

**To Reproduce**
Log into the panel 
Go to server list
Wait

**Expected behavior**
Show an accurate player count per server

**Screenshots**
https://gyazo.com/e50912ced59c70f7e827d65afb708df3

**If you were on Desktop please provide**
 - Win10
 - Edge chromium
 - 2k

**If you were on Mobile please provide:**
 - Device
 - OS
 - Browser
- In browser app or embedded web view.

**Additional context**

**Comment by alliraine** [comment]
Cannot replicate
