### ISSUE TITLE
The side menu with server management options gets too long and won't show you the rest of the options

### ISSUE THREAD

**Issue by rhyderswen** [DedicatedMC/Raw-Power-Panel#29]
**Describe the bug**
If you have too many permissions, the options like console, server details, etc. will eventually cut off without being able to scroll down. The only way to see the rest of the options would be zooming out your web browser.

**To Reproduce**
Give yourself enough permissions to have more than 6 options in the server management tab and try to find the other one or two options. Trying to scroll down results in the right half of the page scrolling instead

**Expected behavior**
You're able to scroll down in the menu and find the other options

**Screenshots**
I don't think any are necessary

**If you were on Desktop please provide**
 - Windows 10 Home
 - Google Chrome version 86.0.4240.111
 - 1920 x 1080p resolution

**If you were on Mobile please provide:**
N/A

**Additional context**
Thank you!

**Comment by Rambopro5** [comment]
Intel i5 windows 10 with 150% scale unable to see as well. Even after reverting scale issue is still there

**Comment by Rambopro5** [comment]
windows 10 home Google Version 86.0.4240.111 1920x1080p. Changed my scale to 125% and now I cant scroll down even after reverting and restarting everything

**Comment by alliraine** [comment]
Fixed
