### ISSUE TITLE
Console Alignment Issues

### ISSUE THREAD

**Issue by Firosee** [DedicatedMC/Raw-Power-Panel#30]
**Describe the bug**
Console is adding an extra > per line in the console, but when refreshed it goes away.

**To Reproduce**
Take a look at the console and when a new activity is added, it will add a > line

**Expected behavior**
The line should not be there

**Screenshots**
(https://gyazo.com/1e2f708baadf6ea9d41468a2843dee7e), also linked like asked.

**If you were on Desktop please provide**
 - OS - Windows 10
 - Browser - Google Chrome Bet

![image](https://user-images.githubusercontent.com/59424511/97120818-dd52b500-1711-11eb-8d2d-8cfe307db027.png)

**Comment by tgb20** [comment]
Not reproducible, will leave here until root cause is found.

**Comment by Firosee** [comment]
Josh has been able to see it happening live and seems to have confirmed its an issue in my ticket, he has let caleb know so i am just awaiting his response now. But yeah it seems like no one else has reported this issue - very weird.

I have loaded the server with 0 plugins and it is still doing this so i dont think its a plugin causing it. Hopefully caleb can shed some light in it when he sees it ;)

**Comment by Firosee** [comment]
All sorted. Was an issue with startup flags for future reference if ever needed.

Needed: -Dterminal.jline=false

**Comment by Firosee** [comment]
This issue is actually with the paperspigot jars, seems to occur with 1.12.2 confirmed by me, and 1.13.2 by taffy.

Using the startup flags suggested above removes all the console formatting, including colors and things like that.

![image](https://user-images.githubusercontent.com/59424511/97792785-ef819700-1bda-11eb-91fa-1577efd4134f.png)

**Comment by MstrTaffy** [comment]
Confirmed. Seems to be an issue with older paper builds. I get the same issue with 1.13.2 paper 639(I think)
