### ISSUE TITLE
Show how many servers the bot is in instead of 0/0 players on top of the console

### ISSUE THREAD

**Issue by Leastrio** [DedicatedMC/Raw-Power-Panel#31]
**Describe the issue that would warrant this feature**
Finding what the number of servers is in. You cant just enter in a command into console to get an amount of servers, you have to add a bit of code to your bot to see that.

**Describe the solution you'd like**
There could be a api that the bot could send stats to every so often(Depending on ratelimits but personally I would be fine with every 5-10 minutes), then that would update the panel with the amount servers the bot is in.

**Describe alternatives you've considered**
There might be a way to send commands through console and have them echo back but I really doubt it. But if there is a way then the panel could use a system to gather servers from there.

**Comment by EgoMaw** [comment]
Currently, it's hidden on non-Minecraft servers
