### ISSUE TITLE
Allow Customers to Allocate Ports

### ISSUE THREAD

**Issue by MstrTaffy** [DedicatedMC/Raw-Power-Panel#32]
**Describe the bug**
The instances have max allocation set to 0 which doesn't allow them to auto allocate ports. There needs to be an retroactive update to the MySQL DB to set Max Allocations from 0 -> 5

There is also not a section that allows it to be set in the setup on WHMCS

**Screenshots**
https://i.taffynet.net/wxmWcAvS7H.png

**Additional context**
Caleb calls it a potty and not a toilet.

**Comment by alliraine** [comment]
updated the database once again. We still need to add that to WHMCS or make it default to a value.

**Comment by alliraine** [comment]
This is going to be a WHMCS issue and I plan on adding it to the WHMCS setup script.
