### ISSUE TITLE
old features are missing on bot host

### ISSUE THREAD

**Issue by iamimpulse08** [DedicatedMC/Raw-Power-Panel#34]
So the syntax error highlighting is now gone from the online file editor, I can't CTRL + S code anymore when I'm done editing which was a nice quality of life feature.

If possible can we get CTRL + S saving back. Syntax isn't a big deal as sometimes there were false positives but sometimes it was useful say for instance if I put a ); instead of ;); or a bit of code was unreachable due to missing {} 

No other alternatives, but it was nice to have those features but now it brings up the save web page thing on chrome.

**Comment by ElijahRus250** [comment]
I agree, the CTRL S was a nice thing to have

**Comment by alliraine** [comment]
Ctrl+S works if the editor is active, like if you are clicked into the editor. I'll look into the syntax thing. :)

**Comment by alliraine** [comment]
This has been done
