### ISSUE TITLE
Changeable file editor size

### ISSUE THREAD

**Issue by Kohi-of-Pride** [DedicatedMC/Raw-Power-Panel#35]
the new text file editor's only issue is that it is small, unlike the old text file editor which was about as big as the console, and this one is about half that size which is inconvenient, at least to me. I like seeing every or most things in the file while editing it, but when the editor is that small it distracts me quite a bunch when editing a yaml or config file of a plugin

Giving it a permanent size might not be best for everyone, perhaps some people would like it to stay small and others, like me want it to be console size. So i suggest that you make it possible for the size to be dragged and made bigger or smaller, with the limits being something around as small as 5 lines and as big as the old editor.

Have a great day

**Comment by ElijahRus250** [comment]
Something like this:
![96885886-07c21b00-1451-11eb-85ff-f50c87880376](https://user-images.githubusercontent.com/64851720/98163867-62c42b00-1eb1-11eb-9ed0-2a336542f3c0.gif)

**Comment by alliraine** [comment]
Yesss. I really want to do this. Right now in my personal dev environment I have it scaling better but I would LOVE to do this. I will look into how to do this.

**Comment by alliraine** [comment]
So in the next version of the panel I have updated the file editor to be as big as the page allows for without scrolling. Once it launches i would love to hear more feedback to decide if it should be resizable or not.

**Comment by ElijahRus250** [comment]
👍

**Comment by alliraine** [comment]
Matthew says no
