### ISSUE TITLE
Additional File Type Support in File Manager

### ISSUE THREAD

**Issue by austin4195** [DedicatedMC/Raw-Power-Panel#36]
**Describe the issue that would warrant this feature**
Forge Servers tend to store a lot of things in .conf and .hocon. The plain text editor is alright for basic tasks but can cause issues when modifying extensively such as changing indention levels, etc.

**Describe the solution you'd like**
Implement syntax support for .hocon and .conf

**Comment by alliraine** [comment]
We plan on replacing the current text editor with another one in the future. This will not be implemented at this time.
