### ISSUE TITLE
Console not scrolling on panel, after error spam

### ISSUE THREAD

**Issue by antibitcoin** [DedicatedMC/Raw-Power-Panel#37]
**Describe the bug**
there is something I don't think it's a bug but rather a limit, when there is an error that keeps repeating on the console spamming it, the console stop scrolling, and u need to refresh the page to see new stuff, even after the error gets fixed and no longer spamming console, the only way to get console back to scroll down is by restarting the server.

**To Reproduce**
Get some plugin to spam lots of errors, console will stop scrolling, and will never scroll again, you will have to keep refreshing the page to check new info, even tho after the spam stops and the errors fix.
than you restart your server and it gets back to normal.

**Expected behavior**
It's expected to keep scrolling or at least start scrolling again on refresh of the page.

**Screenshots**

**If you were on Desktop please provide**
 - windows 10
 - google chrome
 - 1920x1080

**If you were on Mobile please provide:**
 - Device
 - OS
 - Browser
- In browser app or embedded web view.

**Additional context**

**Comment by rhyderswen** [comment]
Can confirm

**Comment by alliraine** [comment]
Fixed upstream. If this is still an issue please create a new issue.
