### ISSUE TITLE
fix breadcrumbs 

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#4]
<img width="345" alt="Screen Shot 2020-10-22 at 10 09 38 AM" src="https://user-images.githubusercontent.com/64851720/96883756-c0d32600-144e-11eb-9ede-c9941adad9a8.png">
<img width="265" alt="Screen Shot 2020-10-22 at 10 09 34 AM" src="https://user-images.githubusercontent.com/64851720/96883758-c0d32600-144e-11eb-853a-9b6a86dd0645.png">
<img width="220" alt="Screen Shot 2020-10-22 at 10 09 30 AM" src="https://user-images.githubusercontent.com/64851720/96883759-c0d32600-144e-11eb-9cb0-dbba5bd3198d.png">

look at the bStats it gets bigger and changes colour multiple times

**Comment by TehloWasTaken** [comment]
This is intentional. The white shows that you're in multiple folders, and the gray shows the actual file you are in. bStats isn't bigger, thats just a visual illusion because of the color change.
