### ISSUE TITLE
Restore Button for backups.

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#42]
**Describe the issue that would warrant this feature**
You can add a restore button to the backups. It will delete all the files and put the ones in from the backup automatically.

**Describe the solution you'd like**
A Restore button on the backups page.
<img width="196" alt="Screen Shot 2020-11-05 at 7 00 45 PM" src="https://user-images.githubusercontent.com/64851720/98309752-469bb900-1f99-11eb-8df7-ba109c93dd3c.png">

**Describe alternatives you've considered**
You could download all the files and re upload BUT it takes a lot of time especially with bigger backups. It would make sense to have:
Backup Server -> Server. (This has no uploading from the client making the speed a lot faster)
Backup Server -> Client -> Server ( this takes a long time with the more upload.

**Comment by alliraine** [comment]
This is going to be added upstream in the nearish future.

**Comment by tgb20** [comment]
This was added to the panel
