### ISSUE TITLE
Storage, Memory and Cpu usage at 0

### ISSUE THREAD

**Issue by grass-muncher** [DedicatedMC/Raw-Power-Panel#44]
**Describe the bug**
A clear and concise description of what the bug is. Provide detail that accurate represents the issue, this should be be a single sentence or a snippet of words. Your title should not contain this key information, rather be a searchable and concise phrase representing the issue.

**To Reproduce**
If your issue is a functionality issue please describe how to recreate it step by step. Its its a UI or interface issue describe where it can be found in the panel.

**Expected behavior**
refreshing page doesn't effect bug but restarting the browser fixes issue.

**Screenshots**
https://cdn.discordapp.com/attachments/635062859344248832/774768572655206430/unknown.png

**If you were on Desktop please provide**
 - windows 10 Home OS build 19041.572
 - Brave
 - 1920*2080

**Comment by alliraine** [comment]
Invalid format. however this bug is an issue with wings that has been resolved upstream
