### ISSUE TITLE
Text Editor Bug. Overlapping side of screen

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#45]
**Describe the bug**
In the text editor files get cut off. I am using full screen and have tried with smaller screens. 

**To Reproduce**
Open up file manager, Create File.

Here you will go about making one large line of text, If your line goes longer than the panel screen it happens. Have tested on Brave & Safari, Please watch this short documentary I made about this bug. As I am not sure how I can explain it in words

Sorry GitHub does not like MP4s, Here is a discord link _I know you do not like discord links, sorry_
https://discord.com/channels/626715201445691392/635062889102966795/776647003840708608

**Expected behavior**
It should start a new line (which it does) just earlier on the page so I will be able to save my file.

**Screenshots**
Above

**If you were on Desktop please provide**
 - MacOs. Big Sur
 - Safari and Brave
 - Full Screen

**If you were on Mobile please provide:**
n/a

**Additional context**
<3

**Comment by alliraine** [comment]
Jesus christ that video

**Comment by EgoMaw** [comment]
This has been fixed as of today
