### ISSUE TITLE
Verify if a player updated a file or if the server updated the file

### ISSUE THREAD

**Issue by rhyderswen** [DedicatedMC/Raw-Power-Panel#46]
**Describe the issue that would warrant this feature**
People could change log files or configs, and in the protection of abuse, we wouldn't know who has updated the file last. Maybe someone hid something in there, but maybe it's just the server adding something to logs.

**Describe the solution you'd like**
Instead of just "22 hours ago" under the latest updated column, maybe add "User updated 22 hours ago" and "Server updated 22 hours ago" and maybe which user updated it. Bonus if you can save file changes like how it works on github. 

**Describe alternatives you've considered**
There really aren't any without special plugins that only do that. Even then, they'd probably have to be custom plugins.

**Comment by EgoMaw** [comment]
While I like this suggestion, there will be a better way to monitor changes made via the panel or its API on your server in the form of Audit Logs.
