### ISSUE TITLE
Backups not being done according to Schedules

### ISSUE THREAD

**Issue by Antlucl** [DedicatedMC/Raw-Power-Panel#47]
**Describe the bug**
Schedules not triggering backups when scheduled to do so; only when done maunally (and backups then fail if done so)

**To Reproduce**
Create a new schedule:
Set first task to be "Delete oldest Backup"
Add second task 5 seconds later "Create backup"
Set a time for it to run (it should not go through if it's the same as for me)
Also try and simply run it manually (for it to fail)

**Expected behavior**
For the oldest backup to be removed and a new one succesfully created.

**Screenshots**
![dedimc2](https://user-images.githubusercontent.com/51057541/99841000-c87d0c00-2b6d-11eb-9ebd-8a8b66e738aa.PNG)
![dedimc1](https://user-images.githubusercontent.com/51057541/99841005-c9ae3900-2b6d-11eb-86a3-ebc12e2d706f.PNG)

**If you were on Desktop please provide**
 - Windows 10
 - Chrome
 - N/A

**Additional context**
According to Taffy the time of the schedule was also lying; for me it said 01:00 UTC however on his end it said 11:00 UTC; however at neither of these two times did a backup get pulled.

**Comment by alliraine** [comment]
Backups have been rewritten since this was created. If this continues make a new issue.
