### ISSUE TITLE
Allow people to view the console, but not send commands

### ISSUE THREAD

**Issue by rhyderswen** [DedicatedMC/Raw-Power-Panel#48]
**Describe the issue that would warrant this feature**
Viewing the console is important for a number of reasons, but having access to sending commands in it can destroy a server, so why not have another permission that only lets you view the console, but not send commands?

**Describe the solution you'd like**
Have a separate permission node in sub-users for only being able to view the console and not send commands.

**Describe alternatives you've considered**
You can get a plugin like DiscordSRV that puts the console in Discord, but plugins like that require an external interface, and sometimes, that isn't ideal.

**Comment by ElijahRus250** [comment]
Already a feature. Just don't give them the "Send Commands" Perm in subusers

**Comment by rhyderswen** [comment]
That's not a perm. The only console permission is simply labeled "console" which allows users to send command, meaning it's all or nothing

**Comment by ElijahRus250** [comment]
Oh, My bad they used to have that.

**Comment by ElijahRus250** [comment]
Was fixed, do not give them the "Console" perm

**Comment by EgoMaw** [comment]
There is an active pull request on pterodactyl/panel#3864.
As soon as it's merged I'll include it in RPP as well
