### ISSUE TITLE
logout button getting cut off

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#5]
https://discord.com/channels/626715201445691392/699478647454695434/768839243425906688

**Comment by alliraine** [comment]
@luckyywastaken please post the image in here.

**Comment by ElijahRus250** [comment]
![Screen_Shot_2020-10-22_at_10 11 23_AM](https://user-images.githubusercontent.com/64851720/97038362-b1c8a280-1538-11eb-8ef9-b1c13d9b1b3c.png)
