### ISSUE TITLE
MySQL Database Password not there

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#50]
**Describe the bug**
on the mysql db page. if you click on a db the password box is gone.

**To Reproduce**
make a db and click the eye

**Expected behavior**
shows the password

**Screenshots**

![image](https://user-images.githubusercontent.com/64851720/102300104-442a6880-3f22-11eb-9d12-dbe6aa2ec04e.png)

**If you were on Desktop please provide**
 - macOS big sur
 - safari
 - full

**Additional context**

**Comment by ElijahRus250** [comment]
also that database has been deleted.

**Comment by alliraine** [comment]
Fixed in release tomorrow
