### ISSUE TITLE
Overlapping elements of the select move thing (see post)

### ISSUE THREAD

**Issue by iamimpulse08** [DedicatedMC/Raw-Power-Panel#51]
![unknown](https://user-images.githubusercontent.com/51331395/103166422-ca478880-4819-11eb-8517-b30090669def.png)

So if I try and select multiple files and scroll down to the bottom of my webpage to select the last file, I can't click on the vast majority of the tickbox
and instead can only click on the very very top of the tickbox, which is a little annoying but it functions.

Issue already known according to Taffy in discord.

**Comment by alliraine** [comment]
Fixed
