### ISSUE TITLE
Click to copy does not work on the port under Network Settings

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#52]
**Describe the issue that would warrant this feature**
On network settings you can click to copy on the IP address but not on the port

**Describe the solution you'd like**
Either add the COC to the port or make it all into one like 1.1.1.1:6969

**Describe alternatives you've considered**
Add the COC to port

**Comment by ElijahRus250** [comment]
![vlRSOc](https://user-images.githubusercontent.com/64851720/104085580-bc810280-521e-11eb-860e-ac95315d61ce.png)
IP ^

![porMA6](https://user-images.githubusercontent.com/64851720/104085595-ce62a580-521e-11eb-8b7b-d469a72c26e6.png)
Port ^

**Comment by alliraine** [comment]
Fixed
