### ISSUE TITLE
Spacing issue on schedule tab

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#53]
**Describe the bug**
on the schedules tab it says https://www.timeanddate.com/worldclock/timezone/utcMar 1st at 3:01AM UTC Time there is no space in-between the link and the text

**To Reproduce**
create schedule, look

**Expected behavior**
should be space

**Screenshots**
<img width="1125" alt="Screen Shot 2021-03-01 at 9 29 18 AM" src="https://user-images.githubusercontent.com/64851720/109510988-9c2c3200-7a70-11eb-8dea-882c769c4504.png">

**If you were on Desktop please provide**
 - macos catalina 
 - safari
 -full

**Additional context**

**Comment by tgb20** [comment]
Fixed
