### ISSUE TITLE
Search on file text box too small

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#55]
**Describe the bug**
on the cmd + f on a file editor, the type box is very small and has a long more space to expand too

**To Reproduce**
open text fille, command f see

**Expected behavior**
text box be bigger

**Screenshots**
<img width="1113" alt="Screen Shot 2021-03-04 at 11 00 54 PM" src="https://user-images.githubusercontent.com/64851720/110065581-7be4c780-7d3d-11eb-87c5-0337f823f56e.png">

**If you were on Desktop please provide**
 - safari
 - Mac
 - full

**Additional context**

**Comment by alliraine** [comment]
We plan on replaced the editor in the future so this isn't worth the time
