### ISSUE TITLE
Server Information panel height messed up

### ISSUE THREAD

**Issue by AppleMacOS** [DedicatedMC/Raw-Power-Panel#57]
**Describe the bug**
The Server Infomation panel height is messed up on Safari

**To Reproduce**
Go to the panel with Safari and click any server, then you'll see the Server Infomation panel height is messed up

**Expected behaviour**
The height should look like this: ![](https://screenz.ca/i/mgL3b4P2fNEyg.png)

**Screenshots**

![](https://screenz.ca/i/1LZjslAT7r4s7.png)

**If you were on Desktop please provide**
 - macOS Big Sur
 - Safari
 - 2560 × 1600

**Additional context**

I found out that if you set the height to 100px instead of 100% it fixes it on Safari. It also doesn't break it on other browsers

**Comment by alliraine** [comment]
Fixed in dev enviroment. Will be updating shortly
