### ISSUE TITLE
[Website] Weird login button visuals

### ISSUE THREAD

**Issue by AriDeve** [DedicatedMC/Raw-Power-Panel#62]
**Describe the bug**
The visuals for the login button in the main page are working weirdly/not working.

**To Reproduce**
Go to the main page https://dedicatedmc.io/ and click on the Login button. It will turn orange and go blank.

**Expected behavior**
Nothing should happen, since it makes a menu when hovered over. Or it should redirect to one of the login choices.

**Screenshots**
![image](https://user-images.githubusercontent.com/37328719/128486672-20b82d34-22d2-431d-a470-06ffa3975ffd.png)

**If you were on Desktop please provide**
 - Windows 10
 - Chrome, version 92.0.4515.131
 - 1920x1080

**Additional context**
This probably happens because there is a style made for when the button is focused, and same with other buttons on the bar, since it goes back to normal after getting unfocused.

**Comment by EgoMaw** [comment]
New Website has replaced the old one so the issue is no longer applicable.
