### ISSUE TITLE
[Website] Blurry images

### ISSUE THREAD

**Issue by AriDeve** [DedicatedMC/Raw-Power-Panel#63]
**Describe the bug**
Many of the logos are blurry on certain browsers because they are downscaled from a larger image, and don't have correct css applied.

**To Reproduce**
Visit any of the websites that have images, for example in https://docs.dedicatedmc.io/ the logo is visibly very blurry.

**Expected behavior**
Sharp looking logos, with no blur.

**Screenshots**
![image](https://user-images.githubusercontent.com/37328719/128488138-8763d408-a198-4f2d-a745-cc90fdd89d82.png)

**If you were on Desktop please provide**
 - Windows 10
 - Chrome, version 92.0.4515.131
 - 1920x1080

**Additional context**
In browsers downscaled images often look blurry, and you should use certain css to fix the issue.

**Comment by tgb20** [comment]
I cannot reproduce this on Chrome, Firefox, or Safari.

**Comment by AriDeve** [comment]
Huh, weird, could be just a me thing then on chrome, but I wouldn't see a reason as to why, since the same happens with extensions off.
As for Firefox, as far as I can remember, they deal with downscaling much better than Chrome.
