### ISSUE TITLE
unix_args.txt not included in backup

### ISSUE THREAD

**Issue by ghost** [DedicatedMC/Raw-Power-Panel#66]
**Describe the bug**
When making a backup using the panel's backup feature on a server installed with Forge, the file `unix_args.txt` is not included in this backup.

**To Reproduce**
Use the backup feature on server installed with Forge.

**Expected behavior**
`unix_args.txt` should be included in the backup.

**Additional context**
Use a server installed with Forge to generate the `unix_args.txt`.

**Comment by EgoMaw** [comment]
This issue has been fixed.
