### ISSUE TITLE
error unzipping world folder in dedicatedmc site

### ISSUE THREAD

**Issue by nathanbarnatt** [DedicatedMC/Raw-Power-Panel#67]
when I unzip my file in the file management section I get this error "(code: 500) (request_id: 4478edab-c194-4f42-9d2b-e36bedc28dc5)"

Not sure what to do.

<img width="1082" alt="Screenshot 2023-09-10 at 11 14 39 AM" src="https://github.com/DedicatedMC/Raw-Power-Panel/assets/121583159/baf7686d-da83-4e1e-940b-b7971d233d2d">
<img width="1101" alt="Screenshot 2023-09-10 at 11 14 50 AM" src="https://github.com/DedicatedMC/Raw-Power-Panel/assets/121583159/1132737f-e611-47bd-b410-280336e19396">

**Comment by EgoMaw** [comment]
Please join our Discord server https://discord.dedicatedmc.io for support!
