### ISSUE TITLE
Add the select all and select none buttons back to the panel

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#8]
<img width="263" alt="Screen Shot 2020-10-22 at 10 33 16 AM" src="https://user-images.githubusercontent.com/64851720/96886877-034a3200-1452-11eb-8efb-c31ec28f068f.png">
these are in the old panel but not in the new one

**Comment by TehloWasTaken** [comment]
Thats what this button is for:
https://i.dedimc.io/CJxm74Mb4Z.gif

**Comment by ElijahRus250** [comment]
Ment to say this is for sub users!! sorry

**Comment by alliraine** [comment]
Not going to do this. I don't want to make it easier for people to give possible damaging permissions to people who shouldn't have them.
