### ISSUE TITLE
Issues in the tab.

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#9]
<img width="696" alt="Screen Shot 2020-10-22 at 10 35 13 AM" src="https://user-images.githubusercontent.com/64851720/96887214-6045e800-1452-11eb-8cc6-cec17ca875c0.png">

This is what s shown on the subsets tab but on all other ones it looks like this.

<img width="697" alt="Screen Shot 2020-10-22 at 10 35 19 AM" src="https://user-images.githubusercontent.com/64851720/96887298-75bb1200-1452-11eb-927a-d17d8337072c.png">

**Comment by alliraine** [comment]
Nice catch!
